package social.fb
{
	public class FacebookPermissions_v1
	{
		
		public static const publish_stream:String = "publish_stream"
		public static const basic_info:String = "basic_info"
		public static const manage_friendlists:String = "manage_friendlists"
		public static const create_event:String = "create_event"
		public static const rsvp_event:String = "rsvp_event"
		public static const sms:String = "sms"
		public static const offline_access:String = "offline_access"
		public static const user_about_me:String = "user_about_me"
		public static const friends_about_me:String = "friends_about_me"
		public static const user_activities:String = "user_activities"
		public static const friends_activities:String = "friends_activities"
		public static const user_birthday:String = "user_birthday"
		public static const friends_birthday:String = "friends_birthday"
		public static const user_education_history:String = "user_education_history"
		public static const friends_education_history:String = "friends_education_history"
		public static const user_events:String = "user_events"
		public static const friends_events:String = "friends_events"
		public static const user_groups:String = "user_groups"
		public static const friends_groups:String = "friends_groups"
		public static const user_hometown:String = "user_hometown"
		public static const friends_hometown:String = "friends_hometown"
		public static const user_interests:String = "user_interests"
		public static const friends_interests:String = "friends_interests"
		public static const user_likes:String = "user_likes"
		public static const friends_likes:String = "friends_likes"
		public static const user_location:String = "user_location"
		public static const friends_location:String = "friends_location"
		public static const user_notes:String = "user_notes"
		public static const friends_notes:String = "friends_notes"
		public static const user_online_presence:String = "user_online_presence"
		public static const friends_online_presence:String = "friends_online_presence"
		public static const user_photo_video_tags:String = "user_photo_video_tags"
		public static const friends_photo_video_tags:String = "friends_photo_video_tags"
		public static const user_photos:String = "user_photos"
		public static const friends_photos:String = "friends_photos"
		public static const user_relationships:String = "user_relationships"
		public static const friends_relationships:String = "friends_relationships"
		public static const user_relationship_details:String = "user_relationship_details"
		public static const friends_relationship_details:String = "friends_relationship_details"
		public static const user_religion_politics:String = "user_religion_politics"
		public static const friends_religion_politics:String = "friends_religion_politics"
		public static const user_status:String = "user_status"
		public static const friends_status:String = "friends_status"
		public static const user_videos:String = "user_videos"
		public static const friends_videos:String = "friends_videos"
		public static const user_website:String = "user_website"
		public static const friends_website:String = "friends_website"
		public static const user_work_history:String = "user_work_history"
		public static const friends_work_history:String = "friends_work_history"
		public static const email:String = "email"
		public static const read_friendlists:String = "read_friendlists"
		public static const read_insights:String = "read_insights"
		public static const read_mailbox:String = "read_mailbox"
		public static const read_requests:String = "read_requests"
		public static const read_stream:String = "read_stream"
		public static const xmpp_login:String = "xmpp_login"
		public static const user_checkins:String = "user_checkins"
		public static const friends_checkins:String = "friends_checkins"
		public static const manage_pages:String = "manage_pages"
		
		public static const ALL:Array = [publish_stream, create_event, rsvp_event, sms, offline_access, user_about_me, friends_about_me, user_activities, friends_activities, user_birthday, friends_birthday, user_education_history, friends_education_history, user_events, friends_events, user_groups, friends_groups, user_hometown, friends_hometown, user_interests, friends_interests, user_likes, friends_likes, user_location, friends_location, user_notes, friends_notes, user_online_presence, friends_online_presence, user_photo_video_tags, friends_photo_video_tags, user_photos, friends_photos, user_relationships, friends_relationships, user_relationship_details, friends_relationship_details, user_religion_politics, friends_religion_politics, user_status, friends_status, user_videos, friends_videos, user_website, friends_website, user_work_history, friends_work_history, email, read_friendlists, read_insights, read_mailbox, read_requests, read_stream, xmpp_login, user_checkins, friends_checkins, manage_pages];
	}
}

